# -*- coding: utf-8 -*-
"""Upload_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r3qjHD_LBnnTJmbPzXYb_tEM8L9rrFeO
"""

import streamlit as st
import pandas as pd

st.title("📥 Upload Dataset Mahasiswa")

# Upload file 1: Survey
survey_file = st.file_uploader("Upload Data Survei Mahasiswa", type=['csv', 'xlsx'])
if survey_file:
    df_survey = pd.read_csv(survey_file) if survey_file.name.endswith('.csv') else pd.read_excel(survey_file)
    st.session_state['df'] = df_survey
    st.subheader("Preview Data Survei")
    st.write(df_survey.head())

# Upload file 2: IPK
ipk_file = st.file_uploader("Upload Data IPK Mahasiswa", type=['csv', 'xlsx'])
if ipk_file:
    df_ipk = pd.read_csv(ipk_file) if ipk_file.name.endswith('.csv') else pd.read_excel(ipk_file)
    st.session_state['df2'] = df_ipk
    st.subheader("Preview Data IPK")
    st.write(df_ipk.head())

# Tombol lanjut ke halaman analisis
if 'df' in st.session_state and 'df2' in st.session_state:
    st.success("✅ Kedua file berhasil diunggah!")
    st.page_link("2_📊_Analisis_Data.py", label="👉 Lanjut ke Analisis", icon="📈")
else:
    st.info("Harap unggah kedua file terlebih dahulu untuk melanjutkan.")